In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train_news.csv')

In [4]:
df.head()

,Unnamed: 0,id,headline,written_by,news,label
0,0,9653,Ethics Questions Dogged Agriculture Nominee as...,Eric Lipton and Steve Eder,"WASHINGTON — In Sonny Perdue’s telling, Geo...",0
1,1,10041,U.S. Must Dig Deep to Stop Argentina’s Lionel ...,David Waldstein,HOUSTON — Venezuela had a plan. It was a ta...,0
2,2,19113,Cotton to House: ’Do Not Walk the Plank and Vo...,Pam Key,"Sunday on ABC’s “This Week,” while discussing ...",0
3,3,6868,"Paul LePage, Besieged Maine Governor, Sends Co...",Jess Bidgood,"AUGUSTA, Me. — The beleaguered Republican g...",0
4,4,7596,A Digital 9/11 If Trump Wins,Finian Cunningham,Finian Cunningham has written extensively on...,1

In [6]:
X=df.drop('label',axis=1)
X.head()

,Unnamed: 0,id,headline,written_by,news
0,0,9653,Ethics Questions Dogged Agriculture Nominee as...,Eric Lipton and Steve Eder,"WASHINGTON — In Sonny Perdue’s telling, Geo..."
1,1,10041,U.S. Must Dig Deep to Stop Argentina’s Lionel ...,David Waldstein,HOUSTON — Venezuela had a plan. It was a ta...
2,2,19113,Cotton to House: ’Do Not Walk the Plank and Vo...,Pam Key,"Sunday on ABC’s “This Week,” while discussing ..."
3,3,6868,"Paul LePage, Besieged Maine Governor, Sends Co...",Jess Bidgood,"AUGUSTA, Me. — The beleaguered Republican g..."
4,4,7596,A Digital 9/11 If Trump Wins,Finian Cunningham,Finian Cunningham has written extensively on...

In [9]:
y=df['label']

In [11]:
y.head()

0    0
1    0
2    0
3    0
4    1
Name: label, dtype: int64

In [13]:
df.shape

(20800, 6)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer

In [17]:
df=df.dropna()
df.head(10)

,Unnamed: 0,id,headline,written_by,news,label
0,0,9653,Ethics Questions Dogged Agriculture Nominee as...,Eric Lipton and Steve Eder,"WASHINGTON — In Sonny Perdue’s telling, Geo...",0
1,1,10041,U.S. Must Dig Deep to Stop Argentina’s Lionel ...,David Waldstein,HOUSTON — Venezuela had a plan. It was a ta...,0
2,2,19113,Cotton to House: ’Do Not Walk the Plank and Vo...,Pam Key,"Sunday on ABC’s “This Week,” while discussing ...",0
3,3,6868,"Paul LePage, Besieged Maine Governor, Sends Co...",Jess Bidgood,"AUGUSTA, Me. — The beleaguered Republican g...",0
4,4,7596,A Digital 9/11 If Trump Wins,Finian Cunningham,Finian Cunningham has written extensively on...,1
6,6,5134,Rapid Evolution Saved This Fish From Pollution...,JoAnna Klein,The State of New Jersey says you can’t eat the...,0
7,7,1504,Alabama Prison Officials Retaliate Against Pri...,Brian Sonenstein,Advocates say prison officials at the Kilby Co...,1
9,9,4203,Can We Live in a Constant State of Love?,Gillian,Leave a reply \nToni Emerson – When we fall in...,1
10,10,11136,Is Hillary a Closet Drunk… New WikiLeak Email ...,V Saxena,BREAKING: Clinton Fixer Reveals Sick Smear Hil...,1
11,11,2150,BLOOMBERG-BACKED PENNSYLVANIA ATTORNEY GENERAL...,Iron Sheik,Home › POLITICS | US NEWS › BLOOMBERG-BACKED P...,1

In [19]:
messages=df.copy()
messages.reset_index(inplace=True)
messages.head(10)

,index,Unnamed: 0,id,headline,written_by,news,label
0,0,0,9653,Ethics Questions Dogged Agriculture Nominee as...,Eric Lipton and Steve Eder,"WASHINGTON — In Sonny Perdue’s telling, Geo...",0
1,1,1,10041,U.S. Must Dig Deep to Stop Argentina’s Lionel ...,David Waldstein,HOUSTON — Venezuela had a plan. It was a ta...,0
2,2,2,19113,Cotton to House: ’Do Not Walk the Plank and Vo...,Pam Key,"Sunday on ABC’s “This Week,” while discussing ...",0
3,3,3,6868,"Paul LePage, Besieged Maine Governor, Sends Co...",Jess Bidgood,"AUGUSTA, Me. — The beleaguered Republican g...",0
4,4,4,7596,A Digital 9/11 If Trump Wins,Finian Cunningham,Finian Cunningham has written extensively on...,1
5,6,6,5134,Rapid Evolution Saved This Fish From Pollution...,JoAnna Klein,The State of New Jersey says you can’t eat the...,0
6,7,7,1504,Alabama Prison Officials Retaliate Against Pri...,Brian Sonenstein,Advocates say prison officials at the Kilby Co...,1
7,9,9,4203,Can We Live in a Constant State of Love?,Gillian,Leave a reply \nToni Emerson – When we fall in...,1
8,10,10,11136,Is Hillary a Closet Drunk… New WikiLeak Email ...,V Saxena,BREAKING: Clinton Fixer Reveals Sick Smear Hil...,1
9,11,11,2150,BLOOMBERG-BACKED PENNSYLVANIA ATTORNEY GENERAL...,Iron Sheik,Home › POLITICS | US NEWS › BLOOMBERG-BACKED P...,1

In [22]:
messages['news'][6]

'Advocates say prison officials at the Kilby Correctional Facility in Alabama turned off the water to Kinetik Justice Amun’s solitary cell after he initiated a hunger strike. Officials then transferred him to the Limestone Correctional Facility, which has a “behavioral modification program” known among prisoners as a “hot bay” dorm in which prisoners are forced to live in pairs in hot and squalid solitary confinement cells.\nKinetik, also known as Robert Earl Counsil, is the second leader of the Free Alabama Movement (FAM) to be transferred to Limestone. FAM is a group of incarcerated people and their families struggling to end prison slavery and shed light on inhumane conditions in Alabama’s prison system.\nJames Plesant, also known as Dhati Khalid, was the first leader to be transferred. Melvin Ray, also known as Bennu Hannibal Ra-Sun, is the last remaining leader of FAM not to be transferred to Limestone.\nAccording to a statement released by the Ordinary People Society, an Alabama-based human rights group for the incarcerated, Kinetik refused meals upon arrival at the Kilby Correctional Facility on October 21. Before the transfer, Kinetik spent three years housed in solitary confinement at the Holman Correctional Facility.\nAs previously reported by Shadowproof, Kilby is said to be a “ bully camp .” When one Alabama prisoner learned of Kinetik’s transfer to Kilby, he explained the prison is where they send those that “they have to iron out with brutality.” He added, “When they send you to Kilby, that’s where they break your arms and break your legs.”\nPrison officials turned off the water to Kinetik’s cell in response to his hunger strike, advocates say. “They are trying to kill him,” argued Pastor Kenneth Glasgow, founder of the Ordinary People Society and an “outside” spokesperson for FAM. The Alabama Department of Corrections did not respond to multiple requests for comment.\nThe Alabama Department of Corrections is currently facing a federal investigation into the rampant violence, overcrowding, and structural decay in its prison system. Kinetik believes his transfer was an act of retaliation by prison officials for his political activity, and that they timed the transfer to prevent him from meeting with this lawyer.\nKinetik is an outspoken advocate for the human rights of the incarcerated. Along with Dhati Khalid and Bennu Hannibal Ra-Sun, Kinetik and the Free Alabama Movement were some of the people behind the call-to-action for the national prison strike against prison slave labor, which began on September 9.\nProminent human rights lawyer and executive director of the Equal Justice Initiative, Bryan Stevenson, announced he will work with Pastor Glasgow and look into Kinetik’s case.\nBennu Hannibal Ra-Sun told Shadowproof the “behavioral modification” dorm or Hot Bay like the one at Limestone is “supposed to be a volunteer program where you volunteer to go into it, but there’s no volunteer aspect. They’re just putting people in it.”\n“You don’t have to have anything specific that you’ve done. They’re not serving you any paperwork, there’s not any kind of due process, and they’re getting funding from it,” he said. “So to justify funding, they have to have bodies.”\n“Really what they’re doing is they’re targeting individuals,” Bennu said. He noted there is a Hot Bay program at Donaldson, where he is incarcerated. “That’s where James Plesant was originally. T hey framed him. They’re constantly framing and jumping on people in that Hot Bay.”\nIn the Hot Bay, prisoners are denied visitation, religious services, recreation, and social services, according to the Free Alabama Movement.\n“[The Hot Bay] is worse than solitary confinement because they take all of your property and you have a cell mate,” Bennu said. “So the one here at Donaldson is two men to a cell. You’re in the cell with another person for 24 hours a day, 7 days a week. Y’all defecating with each other. Y’all urinating with each other, passing gas, burping, sleeping, waking up. Constantly, you’re in the cell with the door locked 24/7 with someone else.”\n“They’re sending you up there, they’re torturing people up there. People first got exposed to the Hot Bay program from Bibb County,” Bennu recalled.\n“There was a bunch of young guys in there. They tore the Hot Bay up,” he said, referring to a July 2015 riot. “They made it where you couldn’t stay in it. They had to get everyone out of there. That’s how bad they are. That’s how bad it was.”\n“A lot of people think that when they say they put us in solitary confinement that it’s solitary confinement. In and of itself, that constitutes the torture. It’s not just putting me in the cell. It’s the conditions that they put me in inside of these cells,” Bennu argued.\nHe continued, “They put us in contaminated cells. What they do is, they have people in solitary and they be complaining about the plumbing or complaining about the lights or the ventilation or something. And they will put us in those cells.”\n“They already know there are issues—there’s plumbing issues, there’s maintenance issues, and they’ll put us in these, what they call ‘black out cells’ or contaminated cells. The lights won’t work, we’ll be in the cells in the dark trying to read, ruining our eyesight. The mattress will be torn up, sleeping on top of these concrete slabs. The water will be leaking, running all over the cell. The vents and stuff are filthy. “\n“It’s all of these elements that are added on, but that doesn’t show up in the paperwork, and that’s what they’ve done to people like myself. They put me in an isolated cell. I’m on what they call, ‘Walk Along Status.’ That means I cannot interact with anyone. I can’t be around another person. Same thing with Kinetik and James Plesant,” Bennu concluded.\nA prisoner previously explained to Shadowproof that Limestone is “where they send everybody and you have to spend one year in isolation.” That prisoner hoped Kilby was not a “layover” on Kinetik’s way to Limestone.\n“If he doesn’t reach Limestone, he’ll be okay,” the prisoner said at the time. According to the website for the Alabama Department of Corrections, Kinetik is now incarcerated at Limestone.\nThe post Alabama Prison Officials Retaliate Against Prison Strike Leader By Cutting Water To Cell appeared first on Shadowproof .\n'

In [24]:
!pip install nltk

Requirement already satisfied: nltk in d:\egde download\lib\site-packages (3.9.1)
Requirement already satisfied: click in d:\egde download\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in d:\egde download\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in d:\egde download\lib\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in d:\egde download\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: colorama in d:\egde download\lib\site-packages (from click->nltk) (0.4.6)

In [25]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [26]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

corpus = []

for article in messages['text']:
    review = re.sub(r'[^a-zA-Z]', ' ', str(article))
    review = review.lower().split()
    review = [ps.stem(word) for word in review if word not in stop_words]
    corpus.append(' '.join(review))

KeyError: 'text'

In [ ]:
corpus[5]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_v = TfidfVectorizer(max_features=5000)
X = tfidf_v.fit_transform(corpus)

In [ ]:
X.shape

In [ ]:
y=messages['label']

In [ ]:
print("X shape:", X.shape)
print("y shape:", y.shape)
print("messages shape:", messages.shape)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [ ]:
tfidf_v.get_feature_names()[:20]

In [ ]:
tfidf_v.get_params()

In [ ]:
count_df = pd.DataFrame(X_train, columns=tfidf_v.get_feature_names())

In [ ]:
count_df.head()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):

In [ ]:
  plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, cm[i, j],
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()

In [ ]:
from sklearn import metrics
import numpy as np
import itertools

In [ ]:
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)
plot_confusion_matrix(cm, classes=['FAKE', 'REAL'])

In [ ]:
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
score

In [ ]:
y_train.shape

In [ ]:
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf = PassiveAggressiveClassifier(n_iter=50)

In [ ]:
linear_clf.fit(X_train, y_train)
pred = linear_clf.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)
plot_confusion_matrix(cm, classes=['FAKE Data', 'REAL Data'])

In [ ]:
classifier=MultinomialNB(alpha=0.1)

In [ ]:
previous_score=0
for alpha in np.arange(0,1,0.1):
    sub_classifier=MultinomialNB(alpha=alpha)
    sub_classifier.fit(X_train,y_train)
    y_pred=sub_classifier.predict(X_test)
    score = metrics.accuracy_score(y_test, y_pred)
    if score>previous_score:
        classifier=sub_classifier
    print("Alpha: {}, Score : {}".format(alpha,score))

In [ ]:
feature_names = cv.get_feature_names()

In [ ]:
classifier.coef_[0]

In [ ]:
sorted(zip(classifier.coef_[0], feature_names), reverse=True)[:20]

In [ ]:
sorted(zip(classifier.coef_[0], feature_names))[:5000]

In [ ]:
hs_vectorizer=HashingVectorizer(n_features=5000,non_negative=True)
X=hs_vectorizer.fit_transform(corpus).toarray()

In [ ]:
X.shape

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [33]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB()
classifier.fit(X_train, y_train)
pred = classifier.predict(X_test)
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)
plot_confusion_matrix(cm, classes=['FAKE', 'REAL'])

NameError: name 'X_train' is not defined